<!-- Directory.Build.props -->
<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Product>SaroHub POS</Product>
    <Company>SaroHub</Company>
    <Version>0.1.0</Version>
    <RollForward>Major</RollForward>
  </PropertyGroup>
</Project>